### ISSUE TITLE
Introduce Dockerfile

### ISSUE THREAD

**Issue by justb81** [ipunkt/fileproxy#11]
Implement with docker, including Dockerfile and docker-compose.yml

**Comment by svensp** [comment]
#12 introduced the Dockerfile to build https://hub.docker.com/r/ipunktbs/fileproxy/
The readme.md already includes instructions how to start the app for development purposes using rancherize.
A production use will have to connect the app to a pre-existing database server

What is the use-case for the docker-compose.yml here?
